# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  scheduled_report_runner:
    class: ScheduledReportRunnerJob
    queue: scheduled_reports
    schedule: every 15 minutes
    description: "Check and execute due scheduled reports"
  
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

development:
  scheduled_report_runner:
    class: ScheduledReportRunnerJob
    queue: scheduled_reports
    schedule: every 15 minutes
    description: "Check and execute due scheduled reports"
  
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
