# config/recurring.yml
# Solid Queue recurring jobs configuration

cache_cleanup:
  class: CacheCleanupJob
  schedule: every 1 hour
  queue: low_priority
  description: "Clean up expired cache entries and enforce size limits"